=== xx979xx/hyundai_meego_system/usr/share/mobile-broadband-provider-info/serviceproviders.2.dtd
<!ELEMENT serviceproviders (country*)>
<!ATTLIST serviceproviders format CDATA #REQUIRED>

<!ELEMENT country (provider*)>
<!ATTLIST country code CDATA #REQUIRED>

<!ELEMENT provider (name+, gsm?, cdma?)>

<!ELEMENT gsm (network-id*, apn+)>
<!ELEMENT apn (name*,
               gateway?,
               username?,
               password?,
               dns*)>
<!ATTLIST apn value CDATA #REQUIRED>

<!ELEMENT network-id EMPTY>
<!ATTLIST network-id mcc CDATA #REQUIRED>
<!ATTLIST network-id mnc CDATA #REQUIRED>

<!ELEMENT username (#PCDATA)> 
<!ELEMENT password (#PCDATA)>
<!ELEMENT dns (#PCDATA)>
<!ELEMENT gateway (#PCDATA)>

<!ELEMENT cdma (name*,
                username?,
                password?,
                dns*,
                sid*)>

<!ELEMENT sid EMPTY>
<!ATTLIST sid value CDATA #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name xml:lang CDATA #IMPLIED>

=== xx979xx/hyundai_meego_system/usr/share/mobile-broadband-provider-info/serviceproviders.xml
<?xml version="1.0"?>
<!-- -*- Mode: XML; tab-width: 4; indent-tabs-mode: t; c-basic-offset: 4 -*- -->
<!DOCTYPE serviceproviders SYSTEM "serviceproviders.2.dtd">

<!-- Authors:
     2008 Antti KaijanmÃ¤ki <antti@kaijanmaki.net>
     2009 Dan Williams <dcbw@redhat.com>
-->

<!-- THIS WORK IS IN PUBLIC DOMAIN:
The person or persons who have associated work with this document
(the "Dedicator" or "Certifier") hereby either (a) certifies that, to the best
of his knowledge, the work of authorship identified is in the public domain of
the country from which the work is published, or (b) hereby dedicates whatever
copyright the dedicators holds in the work of authorship identified below
(the "Work") to the public domain. A certifier, moreover, dedicates any
copyright interest he may have in the associated work, and for these purposes,
is described as a "dedicator" below.

A certifier has taken reasonable steps to verify the copyright status of this
work. Certifier recognizes that his good faith efforts may not shield him from
liability if in fact the work certified is not in the public domain.

Dedicator makes this dedication for the benefit of the public at large and to
the detriment of the Dedicator's heirs and successors. Dedicator intends this
dedication to be an overt act of relinquishment in perpetuity of all present
and future rights under copyright law, whether vested or contingent, in the
Work. Dedicator understands that such relinquishment of all rights includes the
relinquishment of all rights to enforce (by lawsuit or otherwise) those
copyrights in the Work.

Dedicator recognizes that, once placed in the public domain, the Work may be
freely reproduced, distributed, transmitted, used, modified, built upon, or
otherwise exploited by anyone for any purpose, commercial or non-commercial,
and in any way, including by methods that have not yet been invented or
conceived.
-->

<serviceproviders format="2.0">

<!-- United Arab Emirates -->
<country code="ae">
	<provider>
		<name>Etisalat</name>
		<gsm>
			<network-id mcc="424" mnc="02"/>
			<apn value="mnet">
				<name>Etisalat</name>
				<username>mnet</username>
				<password>mnet</password>
				<dns>194.170.1.6</dns>
				<dns>194.170.1.7</dns>
			</apn>
			<apn value="etisalat.ae">
				<name>Etisalat 3G</name>
				<username>etisalat.ae</username>
				<password>etisalat.ae</password>
			</apn>
		</gsm>
	</provider>
</country>

<!-- Albania -->
<country code="al">
	<provider>
		<name>Vodafone</name>
		<gsm>
			<network-id mcc="276" mnc="02"/>
			<apn value="Twa" />
		</gsm>
	</provider>
</country>

<!-- Angola -->
<country code="ao">
	<provider>
		<name>Movinet</name>
		<cdma>
			<username>uname</username>
		</cdma>
	</provider>
	<provider>
		<name>Unitel</name>
		<gsm>
			<network-id mcc="631" mnc="02"/>
			<apn value="internet.unitel.co.ao" />
		</gsm>
	</provider>
</country>

<!-- Argentina -->
<country code="ar">
	<provider>
		<name>Personal</name>
		<gsm>
			<network-id mcc="722" mnc="340"/>
			<apn value="gprs.personal.com">
				<username>gprs</username>
				<password>adgj</password>
				<dns>172.25.7.6</dns>
				<dns>172.25.7.7</dns>
			</apn>
		</gsm>
	</provider>
	<provider>
		<name>Claro</name>
		<gsm>
			<network-id mcc="722" mnc="310"/>
			<network-id mcc="722" mnc="320"/>
			<network-id mcc="722" mnc="330"/>
			<apn value="igprs.claro.com.ar">
				<username>clarogprs</username>
				<password>clarogprs999</password>
				<dns>170.51.255.100</dns>
				<dns>170.51.242.18</dns>
			</apn>
		</gsm>
	</provider>
	<provider>
		<name>Movistar</name>
		<gsm>
			<network-id mcc="722" mnc="010"/>
			<network-id mcc="722" mnc="070"/>
			<apn value="internet.gprs.unifon.com.ar">
				<username>wap</username>
				<password>wap</password>
			</apn>
		</gsm>
	</provider>
</country>

<!-- Austria -->
<country code="at">
	<provider>
		<name>Max</name>
		<gsm>
			<apn value="gprsinternet">
				<name>Max Online</name>
				<username>GPRS</username>
				<dns>213.162.64.1</dns>
				<dns>213.162.64.2</dns>
			</apn>
			<apn value="business.gprsinternet">
				<name>Max Online (Business)</name>
				<username>GPRS</username>
				<dns>213.162.64.1</dns>
				<dns>213.162.64.2</dns>
			</apn>
			<apn value="gprsmetro">
				<name>Max Online (Metro)</name>
				<username>GPRS</username>
				<dns>213.162.64.1</dns>
				<dns>213.162.64.2</dns>
			</apn>
		</gsm>
	</provider>
	<provider>
		<name>Mobilkom/A1</name>
		<gsm>
			<network-id mcc="232" mnc="01"/>
			<apn value="a1.net">
				<username>ppp@a1plus.at</username>
				<password>ppp</password>
				<dns>194.48.139.254</dns>
				<dns>194.48.124.202</dns>
			</apn>
		</gsm>
	</provider>
	<provider>
		<name>T-Mobile</name>
		<gsm>
			<network-id mcc="232" mnc="07"/>
			<network-id mcc="232" mnc="03"/>
			<apn value="gprsinternet">
				<username>t-mobile</username>
				<password>tm</password>
			</apn>
			<apn value="web">
				<name>T-Mobile (formerly tele.ring)</name>
				<username>web@telering.at</username>
				<password>web</password>
				<dns>212.95.31.167</dns>
				<dns>212.95.31.168</dns>
			</apn>
		</gsm>
	</provider>
	<provider>
		<name>Orange</name>
		<gsm>
			<network-id mcc="232" mnc="05"/>
			<apn value="web.one.at">
				<username>web</username>
				<password>web</password>
				<dns>194.24.128.100</dns>
				<dns>194.24.128.102</dns>
			</apn>
		</gsm>
	</provider>
	<provider>
		<name>Three</name>
		<name xml:lang="de">Drei</name>
		<gsm>
			<network-id mcc="232" mnc="10"/>
			<apn value="drei.at"/>
		</gsm>
	</provider>
	<provider>
		<name>Yesss</name>
		<gsm>
			<apn value="web.yesss.at"/>
		</gsm>
	</provider>
</country>

<!-- Australia -->
<country code="au">
	<provider>
		<name>Exetel</name>
		<gsm>
			<apn value="exetel1"/>
		</gsm>
	</provider>
	<provider>
		<name>Optus</name>
		<gsm>
			<network-id mcc="505" mnc="02"/>
			<apn value="internet">
				<dns>202.139.83.3</dns>
				<dns>192.65.91.129</dns>
			</apn>
			<apn value="CONNECT">
				<name>Optus 3G</name>
				<dns>202.139.83.3</dns>
				<dns>192.65.91.129</dns>
			</apn>
		</gsm>
	</provider>
	<provider>
		<name>Telstra</name>
		<gsm>
			<network-id mcc="505" mnc="01"/>
			<apn value="telstra.wap">
				<dns>139.130.4.4</dns>
				<dns>203.50.2.71</dns>
			</apn>
			<apn value="telstra.datapack">
				<name>Telstra (3G data pack)</name>
				<password>Telstra</password>
				<dns>139.130.4.4</dns>
				<dns>203.50.2.71</dns>
			</apn>
			<apn value="telstra.internet">
				<name>Telstra (Next G)</name>
				<dns>139.130.4.4</dns>
				<dns>203.50.2.71</dns>
			</apn>
			<apn value="telstra.pcpack">
				<name>Telstra (3G PC pack - pay by time)</name>
				<password>Telstra</password>
				<dns>139.130.4.4</dns>
				<dns>203.50.2.71</dns>
			</apn>
		</gsm>
	</provider>
	<provider>
		<name>Three</name>
		<gsm>
			<network-id mcc="505" mnc="06"/>
			<apn value="3netaccess">
				<username>a</username>
				<password>a</password>
				<dns>202.124.68.130</dns>
				<dns>202.124.76.66</dns>
			</apn>
			<apn value="3services">
				<name>Three Prepaid</name>
				<username>a</username>
				<password>a</password>
				<dns>202.124.68.130</dns>
				<dns>202.124.76.66</dns>
			</apn>
		</gsm>
	</provider>
	<provider>
		<name>Virgin Mobile</name>
		<gsm>
			<apn value="VirginInternet">
				<username>guest</username>
				<password>guest</password>
				<dns>61.88.88.88</dns>
			</apn>
		</gsm>
	</provider>
	<provider>
		<name>Vodafone</name>
		<gsm>
			<network-id mcc="505" mnc="03"/>
			<apn value="vfinternet.au">
				<name>Postpaid</name>
				<dns>192.189.54.33</dns>
				<dns>210.80.58.3</dns>
			</apn>
			<apn value="vfprepaymbb">
				<name>Prepaid</name>
			</apn>
		</gsm>
	</provider>
</country>

<!-- Azerbaijan -->
<country code="az">
	<provider>
		<name>Azercell</name>
		<gsm>
			<network-id mcc="400" mnc="01"/>
			<apn value="internet"/>
		</gsm>
	</provider>
	<provider>
		<name>Bakcell</name>
		<gsm>
			<network-id mcc="400" mnc="02"/>
			<apn value="mms"/>
		</gsm>
	</provider>
</country>

<!-- Bosnia & Herzegovina -->
<country code="ba">
	<provider>
		<name>BH GSM</name>
		<gsm>
			<network-id mcc="218" mnc="90"/>
			<apn value="mms.bhmobile.ba"/>
		</gsm>
	</provider>
</country>

<!-- Barbados -->
<country code="bb">
	<provider>
		<name>Digicel</name>
		<gsm>
			<network-id mcc="342" mnc="750"/>
			<apn value="isp.digicelbarbados.com"/>
		</gsm>
	</provider>
</country>

<!-- Bangladesh -->
<country code="bd">
	<provider>
		<name>AKTel</name>
		<gsm>
			<network-id mcc="470" mnc="02"/>
			<apn value="internet">
				<name>Internet</name>
				<dns>192.168.23.7</dns>
			</apn>
		</gsm>
	</provider>
	<provider>
		<name>Banglalink</name>
		<gsm>
			<network-id mcc="470" mnc="03"/>
			<apn value="blweb">
				<name>Web</name>
				<dns>10.10.55.34</dns>
			</apn>
		</gsm>
	</provider>
	<provider>
		<name>GrameenPhone</name>
		<gsm>
			<network-id mcc="470" mnc="01"/>
			<apn value="gpinternet">
				<dns>202.56.4.120</dns>
				<dns>202.56.4.121</dns>
			</apn>
		</gsm>
	</provider>
	<provider>
		<name>Warid</name>
		<gsm>
			<network-id mcc="470" mnc="07"/>
			<apn value="internet">
				<name>Internet</name>
				<dns>10.6.0.2</dns>
			</apn>
		</gsm>
	</provider>
</country>

<!-- Belgium -->
<country code="be">
	<provider>
		<name>Mobistar</name>
		<gsm>
			<network-id mcc="206" mnc="10"/>
			<apn value="web.pro.be">
				<name>Business</name>
				<username>mobistar</username>
				<password>mobistar</password>
				<dns>212.65.63.10</dns>
				<dns>212.65.63.145</dns>
			</apn>
			<apn value="internet.be">
				<name>Personal</name>
				<username>mobistar</username>
				<password>mobistar</password>
				<dns>212.65.63.10</dns>
				<dns>212.65.63.145</dns>
			</apn>
			<apn value="iew.be">
				<name>Internet Everywhere</name>
				<username>mobistar</username>
				<password>mobistar</password>
				<dns>212.65.63.10</dns>
				<dns>212.65.63.145</dns>
			</apn>
		</gsm>
	</provider>
	<provider>
		<name>Telenet Mobile</name>
		<gsm>
			<network-id mcc="206" mnc="10"/>
